"""
Export daily best bets for the Sports Picks Grid aggregator.

Reads processed/upcoming_enriched.json (generated by scripts/tt_precompute.py)
and writes data_files/best_bets_today.json in the unified schema.
"""
from __future__ import annotations

import json
from datetime import datetime, date, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENRICHED_PATH = ROOT / "processed" / "upcoming_enriched.json"
OUT_PATH = ROOT / "data_files" / "best_bets_today.json"

# Map confidence label → tier
TIER_MAP = {
    "High":   "Strong",
    "Medium": "Good",
    "Low":    "Standard",
}

# Minimum confidence labels to include (Standard picks are hidden in the dashboard)
INCLUDE_CONF = {"High"}   # Medium produces too many low-edge picks; can re-enable later
MIN_WIN_PCT = 0.65        # Only export picks where the model has ≥ 65% win probability

LOOKAHEAD_DAYS = 2       # TT fixtures are dense; look at just today + tomorrow


def _parse_win_pct(val: str | float | None) -> float:
    """Convert '65%' or 0.65 to 0.65."""
    if val is None:
        return 0.5


def _parse_edge(val: str | float | None) -> float | None:
    if val is None or str(val).strip() in {"", "—"}:
        return None
    try:
        parsed = float(str(val).strip().replace("%", "").replace("+", ""))
        return parsed / 100.0 if abs(parsed) > 1.0 else parsed
    except ValueError:
        return None
    if isinstance(val, (int, float)):
        v = float(val)
        return v / 100.0 if v > 1.0 else v
    cleaned = str(val).strip().rstrip("%")
    try:
        v = float(cleaned)
        return v / 100.0 if v > 1.0 else v
    except ValueError:
        return 0.5


def main() -> None:
    if not ENRICHED_PATH.exists():
        print(f"[tt export] {ENRICHED_PATH} not found — writing empty output")
        bets: list[dict] = []
    else:
        with open(ENRICHED_PATH, encoding="utf-8") as f:
            raw = json.load(f)

        # File may be {"generated_at": ..., "fixtures": [...]} or a plain list
        if isinstance(raw, dict):
            records = raw.get("fixtures", raw.get("bets", []))
        else:
            records = raw

        today = date.today()
        cutoff = today + timedelta(days=LOOKAHEAD_DAYS)
        bets = []

        for rec in records:
            raw_date = rec.get("_date") or rec.get("Date", "")
            try:
                match_date = date.fromisoformat(str(raw_date)[:10])
            except ValueError:
                continue

            if not (today <= match_date <= cutoff):
                continue

            conf_label = rec.get("_conf_label", "")
            if conf_label not in INCLUDE_CONF:
                continue

            favourite = rec.get("Favourite", "")
            if not favourite:
                continue

            win_pct = _parse_win_pct(rec.get("Win %"))
            if win_pct < MIN_WIN_PCT:
                continue
            # A betting edge requires an archived price; never substitute a
            # generic break-even assumption for a missing market snapshot.
            edge_value = _parse_edge(rec.get("Model Edge"))
            odds_value = str(rec.get("DraftKings Odds", "")).strip()
            if edge_value is None or odds_value in {"", "—"}:
                continue
            edge = round(edge_value, 4)
            if edge >= 0.06:
                tier = "Elite"
            elif edge >= 0.03:
                tier = "Strong"
            elif edge >= 0.01:
                tier = "Good"
            else:
                tier = "Standard"

            home = rec.get("Home", "")
            away = rec.get("Away", "")
            game_str = f"{home} vs {away}" if home and away else favourite
            tournament = rec.get("Tournament", "")
            game_time = rec.get("Time", "")

            bets.append({
                "game_date":  match_date.isoformat(),
                "game":       game_str,
                "game_time":  game_time,
                "bet_type":   "moneyline",
                "pick":       favourite,
                "confidence": round(win_pct, 4),
                "edge":       edge,
                "odds":       odds_value,
                "tier":       tier,
                "notes":      f"{tournament} · paper-only · {rec.get('Value Alert', '')}",
            })

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "meta": {
            "sport":         "TableTennis",
            "generated_at":  datetime.now(timezone.utc).isoformat(),
            "model_version": "1.0.0",
            "season":        str(datetime.now(timezone.utc).year),
        },
        "bets": bets,
    }
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)
    print(f"[tt export] Wrote {len(bets)} bets → {OUT_PATH}")


if __name__ == "__main__":
    main()
